# Generated by Django 3.1.6 on 2021-02-19 12:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_empleado_habilidades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='empleado',
            name='curriculum',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
